export interface Product {
    name: String,
  description: String,
  category: String,
  type: String,
  price: Number,
  pricePerUnit: Number,
  ingredients: String,
  edibleLine: String,
  edibleClass: String,
  picture: String,
  year: Date,
  measurementUnit: String,
  quantity: Number,
  nationality: String,
  restaurantId: Array<Number>,
  providerId: Array<Number>,
  brandId: String,
}
